source 'http://rubygems.org'

gem 'rails', '3.0.0'
gem 'rake', '0.8.7'
gem 'rack', '1.2.1'
gem 'capistrano', '2.9.0'
gem 'highline', '1.6.21'
gem 'rjb'
gem 'rubygems-update', '1.4.2'
gem 'daemon_controller'
gem 'fastthread'
gem 'json'
gem 'timecop'
gem 'omniauth-saml'
gem 'rdoc'
gem 'couchrest_extended_document'
group :development, :test do
  gem 'test-unit', '1.2.3'
  gem 'rspec-rails', '1.3'
end
