<% database_prefix = nil %>
<% database_suffix = RAILS_ENV %>

base: &base
 database: <%= [database_prefix, "projects", database_suffix].compact.join("_") %> 
 host: localhost
 port: 5984
 
development:
  <<: *base
  
test:
  <<: *base
  
production:
  <<: *base